- hosts: localhost
  pre_tasks:
  - name: apt update && apt upgrade
    become: true
    apt:
      update_cache: true
      upgrade: true
  tasks:
    - name: install apt packages
      become: true
      apt:
        name: [ "git", "neovim", "stow", "flatpak", "cloc", "imagemagick", "entr", "libssl-dev", "zsh" ]
    - name: change shell
      user: name=user shell=/usr/bin/zsh
    - name: install libssl1.1
      become: true
      shell: wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb &&
        dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
    - name: copy passwords
      copy:
        src: "./Passwords.kdbx"
        dest: "/home/user/Passwords.kdbx"
          #    - include: tasks/install-ferdium.yaml
    - include: tasks/setup-ssh.yaml
    - include: tasks/setup-gpg.yaml
    - include: tasks/setup-dotfiles.yaml
    - include: tasks/install-rust.yaml
    - include: tasks/install-solana.yaml
    - name: install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        creates=/home/user/.nvm/nvm.sh
    - name: Install node LTS
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts"
        creates=/home/user/.nvm/alias
    - name: install yarn
      npm:
        name: yarn
        global: yes
    - name: install just
      shell: cargo install just
    - name: install avm
      shell: cargo install --git https://github.com/project-serum/anchor avm --locked
    - name: install anchor
      shell: avm install latest && avm use latest

