- hosts: localhost
  pre_tasks:
  - name: apt update && apt upgrade
    become: true
    apt:
      update_cache: true
      upgrade: true
  tasks:
    - name: install apt packages
      become: true
      apt:
        name: [ "git", "neovim", "stow", "flatpak", "cloc" ]
    - name: copy passwords
      copy:
        src: "./Passwords.kdbx"
        dest: "/home/user/Passwords.kdbx"
    - include: tasks/install-ferdium.yaml
    - include: tasks/setup-ssh.yaml
    - include: tasks/setup-gpg.yaml
    - include: tasks/setup-dotfiles.yaml
    - include: tasks/install-rust.yaml
    - include: tasks/install-solana.yaml
