- name: Add the flathub flatpak repository remote to the user installation
  become: true
  shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: install Ferdium
  flatpak:
    name: org.ferdium.Ferdium
    state: present
