- name: create .ssh directory
  file:
    dest: "/home/user/.ssh"
    mode: 0700
    state: directory
- name: copy public ssh key
  copy:
    src: "./ssh/id.pub"
    dest: "/home/user/.ssh/id_rsa.pub"
    mode: 0644
- name: copy private ssh key
  copy:
    src: "./ssh/id"
    dest: "/home/user/.ssh/id_rsa"
    mode: 0600
