- name: clone .dotfiles
  git:
    repo: "git@github.com:metaproph3t/.dotfiles.git"
    dest: "/home/user/.dotfiles"
    recursive: true
    update: yes
    version: main
- name: remove zshrc
  file:
    path: /home/user/.zshrc
    state: absent
- name: stow dotfiles
  shell: cd /home/user/.dotfiles && stow nvim git zsh --dotfiles
